version: '3.8'
services:
  redis:
      container_name: redis
      image: redis:7.0.4
      restart: unless-stopped
      ports:
        - "6379:6379"
      networks:
        - app-network
  mongo:
      container_name: mongo
      image: mongo:4.0.11
      restart: always
      hostname: mongo
      volumes:
        - ./data:/data
      ports:
        - "27017:27017"
      logging:
        driver: none
      networks:
        - app-network
      healthcheck:
        test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
        interval: 10s
        timeout: 10s
        retries: 5
        start_period: 10s
networks:
  app-network:
    driver: bridge